# SPDX-FileCopyrightText: The discro authors
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: build-and-test

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # The cache should not be shared between different workflows and jobs.
          shared-key: ${{ github.workflow }}-${{ github.job }}

      - name: Check WASM target with `tokio`
        run: >-
          cargo check --locked --features tokio --target wasm32-unknown-unknown

      - name: Build tests with `tokio`
        run: >-
          cargo test --locked --features tokio
          --no-run

      - name: Run tests with `tokio`
        run: >-
          cargo test --locked --features tokio
          -- --nocapture --quiet
