# SPDX-FileCopyrightText: The discro authors
# SPDX-License-Identifier: CC0-1.0

# Same as file name
name: dependency-audit

permissions:
  contents: read

on:
  push:
    paths:
      - "**/Cargo.toml"
  schedule:
    # Weekly, i.e. on Sunday at 13:37 UTC
    - cron: "37 13 * * 0"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          # Keep in sync with `Cargo.toml`.
          rust-version: "1.75"
          command: check
          arguments: >-
            --all-features
            --locked
